// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dist_tourist
double dist_tourist(DataFrame x, DataFrame y, DataFrame dist_file);
RcppExport SEXP _fuzzyclara_dist_tourist(SEXP xSEXP, SEXP ySEXP, SEXP dist_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type y(ySEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_file(dist_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_tourist(x, y, dist_file));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fuzzyclara_dist_tourist", (DL_FUNC) &_fuzzyclara_dist_tourist, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fuzzyclara(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
