# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_tourist <- function(x, y, dist_file) {
    .Call('_fuzzyclara_dist_tourist', PACKAGE = 'fuzzyclara', x, y, dist_file)
}

