
on:
  push:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: Open Journals PDF Generator

jobs:
  JOSS-pdf-generator:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: openjournals/openjournals-draft-action@v.1.0